### ISSUE TITLE
Scroll problem after modal on modal

### ISSUE THREAD

**Issue by oliverkan** [wxsms/uiv#167]
### Version & browser
Chrome Version 64.0.3282.167

### Which component
Modal

### Steps to reproduce the problem
When we open a modal on an existing modal and close last modal then we lose scroll.

**Comment by wxsms** [comment]
pls provide a minimal reproduce. like jsFiddle or codepen.

**Comment by MyHeartsECO** [comment]
@wxsms we're also having this problem on production.  

Scenario: modal on modal, as you provided in https://uiv.wxsm.space/modal "nested modals", but they are in different components. So it's not like 1 component has 5 modals but 2 components have 2 separate modals. When you close one of them, body loses the class `modal-open`, hence the scroll problem arises.

By the way the example you provided in https://uiv.wxsm.space/modal "nested modals" is working fine on us. I can provide you a jsFiddle if you can't reproduce this. Thanks!

**Comment by wxsms** [comment]
@MyHeartsECO @oliverkan 

It is not design to work like that. pls follow the document example.

If you found any reason that they must be 'nested' into 1 component, pls let me know.

**Comment by MyHeartsECO** [comment]
@wxsms can you provide me a template uiv jsFiddle with modal? So I can continue on that and show you what I mean.

**Comment by wxsms** [comment]
@MyHeartsECO https://codepen.io/wxsm/pen/VMGRwG

**Comment by MyHeartsECO** [comment]
@wxsms here it is: https://codepen.io/MyHeartsECO/pen/GQGQZa

So if you open 2nd modal you'll see 2nd modal is behind the backdrop. We've handled it by overriding backdrop z-index with a dirty way but I didn't add the code. Though still, when you close that modal, body loses "modal-open" class, which creates the "scroll problem".

I do realize that nested modals don't work this way but I think people need this way because your example (on github pages) needs to be `componentized`. When you write your modals like that, one below another, it becomes really complex and hard to read in a real world application, hence we used components inside modals.

**Comment by wxsms** [comment]
@MyHeartsECO 

I see. Thanks.

I will try to fix this by adding some prop like `append-to-body`. And when you want to use nested modals like that, you have to make it **append to body**.

like this: http://element.eleme.io/#/en-US/component/dialog#nested-dialog

**Comment by MyHeartsECO** [comment]
@wxsms this solved the z-index issue, thanks! Though we're still facing with `modal-open` problem. When you close the inner-modal, that has `append-to-body:true`, body loses `modal-open` class. I couldn't manage to provide a codepen, bug doesn't occur there which is weird.

**Comment by MyHeartsECO** [comment]
We've found that it was our side of a problem. Thanks @wxsms for your instant update.

**Comment by wxsms** [comment]
@MyHeartsECO  welcome.

**Comment by MyHeartsECO** [comment]
@wxsms sorry to bother you again, but we've faced the same problem on MessageBoxes.  

So scenario is:  

1. Open a modal
2. Display a messageBox on it
3. Close the messageBox
4. Modal loses the focus (body loses `modal-open` class).  

I think this is a lot trickier because we cannot know if there is a modal already open when the time MessageBox is opened/closed. Maybe we can check if the body has `modal-open` class, what do you think? 

I can open another issue for that if you like it.

**Comment by wxsms** [comment]
@MyHeartsECO pls create a new issue for it. thanks.
